services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Senh4Dever4sEfic4z!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  webapp:
    build:
      context: .
      dockerfile: CarDealershipManager.App/Dockerfile
    container_name: CarDealershipManager
    depends_on:
      - sqlserver
      - redis
    ports:
      - "5206:80"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=CarDealershipDB;User Id=sa;Password=Senh4Dever4sEfic4z!;TrustServerCertificate=True;"
      ConnectionStrings__Redis: "redis:6379"
      ASPNETCORE_URLS: "http://+:80"